// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/extensions/filters/http/header_rewrite/header_rewrite.proto

package header_rewrite

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HeaderRewrite with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HeaderRewrite) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HeaderRewrite with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HeaderRewriteMultiError, or
// nil if none found.
func (m *HeaderRewrite) ValidateAll() error {
	return m.validate(true)
}

func (m *HeaderRewrite) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetConfig()) < 1 {
		err := HeaderRewriteValidationError{
			field:  "Config",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return HeaderRewriteMultiError(errors)
	}

	return nil
}

// HeaderRewriteMultiError is an error wrapping multiple validation errors
// returned by HeaderRewrite.ValidateAll() if the designated constraints
// aren't met.
type HeaderRewriteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HeaderRewriteMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HeaderRewriteMultiError) AllErrors() []error { return m }

// HeaderRewriteValidationError is the validation error returned by
// HeaderRewrite.Validate if the designated constraints aren't met.
type HeaderRewriteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HeaderRewriteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HeaderRewriteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HeaderRewriteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HeaderRewriteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HeaderRewriteValidationError) ErrorName() string { return "HeaderRewriteValidationError" }

// Error satisfies the builtin error interface
func (e HeaderRewriteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHeaderRewrite.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HeaderRewriteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HeaderRewriteValidationError{}
