// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: envoy/extensions/filters/network/connection_limit/v3/connection_limit.proto

package connection_limitv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [#next-free-field: 6]
type ConnectionLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The prefix to use when emitting :ref:`statistics
	// <config_network_filters_connection_limit_stats>`.
	StatPrefix string `protobuf:"bytes,1,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// The max connections configuration to use for new incoming connections that are processed
	// by the filter's filter chain. When max_connection is reached, the incoming connection
	// will be closed after delay duration.
	MaxConnections *wrapperspb.UInt64Value `protobuf:"bytes,2,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	// The delay configuration to use for rejecting the connection after some specified time duration
	// instead of immediately rejecting the connection. That way, a malicious user is not able to
	// retry as fast as possible which provides a better DoS protection for Envoy. If this is not present,
	// the connection will be closed immediately.
	Delay *durationpb.Duration `protobuf:"bytes,3,opt,name=delay,proto3" json:"delay,omitempty"`
	// Runtime flag that controls whether the filter is enabled or not. If not specified, defaults
	// to enabled.
	RuntimeEnabled   *v3.RuntimeFeatureFlag            `protobuf:"bytes,4,opt,name=runtime_enabled,json=runtimeEnabled,proto3" json:"runtime_enabled,omitempty"`
	ConnectionBudget *ConnectionLimit_ConnectionBudget `protobuf:"bytes,5,opt,name=connection_budget,json=connectionBudget,proto3" json:"connection_budget,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionLimit) Reset() {
	*x = ConnectionLimit{}
	mi := &file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionLimit) ProtoMessage() {}

func (x *ConnectionLimit) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionLimit.ProtoReflect.Descriptor instead.
func (*ConnectionLimit) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionLimit) GetStatPrefix() string {
	if x != nil {
		return x.StatPrefix
	}
	return ""
}

func (x *ConnectionLimit) GetMaxConnections() *wrapperspb.UInt64Value {
	if x != nil {
		return x.MaxConnections
	}
	return nil
}

func (x *ConnectionLimit) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *ConnectionLimit) GetRuntimeEnabled() *v3.RuntimeFeatureFlag {
	if x != nil {
		return x.RuntimeEnabled
	}
	return nil
}

func (x *ConnectionLimit) GetConnectionBudget() *ConnectionLimit_ConnectionBudget {
	if x != nil {
		return x.ConnectionBudget
	}
	return nil
}

// Opt this filter into a named, dynamically-rebalanced connection budget managed by the
// :ref:`envoy.resource_monitors.per_listener_downstream_connections
// <envoy_v3_api_msg_extensions.resource_monitors.per_listener_downstream_connections.v3.PerListenerDownstreamConnectionsConfig>`
// resource monitor. When set and a budget with the matching “name“ is configured in the
// overload manager, the rebalancer overrides this filter's “max_connections“ on every
// overload manager refresh tick. When absent, the filter runs with the static
// “max_connections“ above and is unaffected by any monitor.
//
// Note on “stat_prefix“: chains on the same listener that join the same budget must share the
// same “stat_prefix“ — they are summed into one budget participant. Two different listeners,
// however, must each use a distinct “stat_prefix“ when joining the same budget. A cross-
// listener collision (typo / copy-paste) is rejected at listener warm with an
// “EnvoyException“; the two listeners would otherwise silently pool their quota under a
// single participant and lose tenant isolation.
type ConnectionLimit_ConnectionBudget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the budget to join. Must match the “name“ field of a configured
	// “PerListenerDownstreamConnectionsConfig“.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Per-listener priority used by the budget under pressure (see
	// :ref:`PerListenerDownstreamConnectionsConfig.pressure_threshold
	// <envoy_v3_api_field_extensions.resource_monitors.per_listener_downstream_connections.v3.PerListenerDownstreamConnectionsConfig.pressure_threshold>`).
	// Optional, in [0.0, 1.0]. When the field is omitted entirely the listener behaves as if
	// “weight = 1.0“ (normal priority). An explicit “weight: 0.0“ is distinguishable from
	// unset and means "fully evict this listener under pressure" (the budget grants zero,
	// including the “min_listener_quota“ floor). Intermediate values scale the listener's
	// demand at every rebalance tier under pressure. Has no effect while pressure is at or
	// below “pressure_threshold“.
	Weight *wrapperspb.DoubleValue `protobuf:"bytes,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// Optional hard ceiling on the per-listener allocation. If set, the budget will never
	// assign this listener more than “max_connections“, regardless of the 5-tier output or
	// pressure weighting. Capacity that would have exceeded the ceiling flows back into the
	// budget within the same rebalance pass and is distributed to other participating
	// listeners that still have headroom (no stranded capacity except when every uncapped
	// listener is itself saturated). Must be “>= min_listener_quota“ (rejected at filter
	// registration otherwise).
	MaxConnections *wrapperspb.UInt64Value `protobuf:"bytes,3,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionLimit_ConnectionBudget) Reset() {
	*x = ConnectionLimit_ConnectionBudget{}
	mi := &file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionLimit_ConnectionBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionLimit_ConnectionBudget) ProtoMessage() {}

func (x *ConnectionLimit_ConnectionBudget) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionLimit_ConnectionBudget.ProtoReflect.Descriptor instead.
func (*ConnectionLimit_ConnectionBudget) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConnectionLimit_ConnectionBudget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectionLimit_ConnectionBudget) GetWeight() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *ConnectionLimit_ConnectionBudget) GetMaxConnections() *wrapperspb.UInt64Value {
	if x != nil {
		return x.MaxConnections
	}
	return nil
}

var File_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto protoreflect.FileDescriptor

const file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDesc = "" +
	"\n" +
	"Kenvoy/extensions/filters/network/connection_limit/v3/connection_limit.proto\x124envoy.extensions.filters.network.connection_limit.v3\x1a\x1fenvoy/config/core/v3/base.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xe6\x04\n" +
	"\x0fConnectionLimit\x12(\n" +
	"\vstat_prefix\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"statPrefix\x12N\n" +
	"\x0fmax_connections\x18\x02 \x01(\v2\x1c.google.protobuf.UInt64ValueB\a\xfaB\x042\x02(\x01R\x0emaxConnections\x12/\n" +
	"\x05delay\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x05delay\x12Q\n" +
	"\x0fruntime_enabled\x18\x04 \x01(\v2(.envoy.config.core.v3.RuntimeFeatureFlagR\x0eruntimeEnabled\x12\x83\x01\n" +
	"\x11connection_budget\x18\x05 \x01(\v2V.envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.ConnectionBudgetR\x10connectionBudget\x1a\xce\x01\n" +
	"\x10ConnectionBudget\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12M\n" +
	"\x06weight\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueB\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\x06weight\x12N\n" +
	"\x0fmax_connections\x18\x03 \x01(\v2\x1c.google.protobuf.UInt64ValueB\a\xfaB\x042\x02(\x01R\x0emaxConnectionsB\xd4\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"Bio.envoyproxy.envoy.extensions.filters.network.connection_limit.v3B\x14ConnectionLimitProtoP\x01Zngithub.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/connection_limit/v3;connection_limitv3b\x06proto3"

var (
	file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDescOnce sync.Once
	file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDescData []byte
)

func file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDescGZIP() []byte {
	file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDesc), len(file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDesc)))
	})
	return file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDescData
}

var file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_goTypes = []any{
	(*ConnectionLimit)(nil),                  // 0: envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit
	(*ConnectionLimit_ConnectionBudget)(nil), // 1: envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.ConnectionBudget
	(*wrapperspb.UInt64Value)(nil),           // 2: google.protobuf.UInt64Value
	(*durationpb.Duration)(nil),              // 3: google.protobuf.Duration
	(*v3.RuntimeFeatureFlag)(nil),            // 4: envoy.config.core.v3.RuntimeFeatureFlag
	(*wrapperspb.DoubleValue)(nil),           // 5: google.protobuf.DoubleValue
}
var file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_depIdxs = []int32{
	2, // 0: envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.max_connections:type_name -> google.protobuf.UInt64Value
	3, // 1: envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.delay:type_name -> google.protobuf.Duration
	4, // 2: envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.runtime_enabled:type_name -> envoy.config.core.v3.RuntimeFeatureFlag
	1, // 3: envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.connection_budget:type_name -> envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.ConnectionBudget
	5, // 4: envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.ConnectionBudget.weight:type_name -> google.protobuf.DoubleValue
	2, // 5: envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.ConnectionBudget.max_connections:type_name -> google.protobuf.UInt64Value
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_init() }
func file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_init() {
	if File_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDesc), len(file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_msgTypes,
	}.Build()
	File_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto = out.File
	file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_goTypes = nil
	file_envoy_extensions_filters_network_connection_limit_v3_connection_limit_proto_depIdxs = nil
}
