// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: envoy/extensions/resource_monitors/listener_budget/v3/listener_budget.proto

package listener_budgetv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Per-listener, priority-aware limits driven by overload manager pressure. Filters join the
// budget with a :ref:`ListenerBudgetParticipant
// <envoy_v3_api_msg_extensions.common.listener_budget.v3.ListenerBudgetParticipant>` block;
// every filter chain of one listener, per kind of filter, forms one participant. On every
// overload manager refresh tick the budget recomputes each participant's limit, which the filters
// enforce on every new connection or request.
//
// The pressure input is the value of the “envoy.overload_actions.listener_budget_pressure“
// overload action, in [0, 1]; it is 0 when the action is not configured. For example, to shed
// between 60% and 80% of host CPU:
//
// .. code-block:: yaml
//
//	actions:
//	- name: envoy.overload_actions.listener_budget_pressure
//	  triggers:
//	  - name: envoy.resource_monitors.cpu_utilization
//	    scaled:
//	      scaling_threshold: 0.6
//	      saturation_threshold: 0.8
//
// On each tick, with “u“ the participant's peak usage since the previous tick and “L“ its
// current limit, all limits clamped to the participant's “[min, max]“:
//
//   - Pressure 0: “L“ becomes “u + burst_headroom“, and “L * growth_factor“ if “u“ reached
//     “L“ (the participant was rejecting).
//   - Pressure “p“ above 0: no limit grows. “LOW“ participants are cut by
//     “min(1, p / live_squeeze_start) * max_decrease“ of their usage per tick and sit at their
//     floor once “p“ reaches “live_squeeze_start“. Beyond that point, the total usage of the
//     “LIVE“ participants of each unit is reduced by “s * max_decrease“ per tick, with “s“ the
//     pressure rescaled from “[live_squeeze_start, 1]“ to “[0, 1]“, taken only from the
//     participants above their weighted max-min fair share.
//
// The budget reads the action on its refresh tick, i.e. one tick after the trigger fired. The
// monitor reports that pressure as its own resource usage; do not trigger actions on it.
//
// At most one “envoy.resource_monitors.listener_budget“ monitor can be configured per bootstrap.
// [#next-free-field: 6]
type ListenerBudgetConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the budget, used by the filters to join it.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Default room granted above a participant's peak usage, in the participant's own unit. Size it
	// to what the pod can absorb in one refresh tick.
	DefaultBurstHeadroom uint64 `protobuf:"varint,2,opt,name=default_burst_headroom,json=defaultBurstHeadroom,proto3" json:"default_burst_headroom,omitempty"`
	// Factor applied to the limit of a participant that reached it, on a tick without pressure.
	// Defaults to 2.0.
	GrowthFactor *wrapperspb.DoubleValue `protobuf:"bytes,3,opt,name=growth_factor,json=growthFactor,proto3" json:"growth_factor,omitempty"`
	// Fraction of usage removed per tick at full pressure. Defaults to 0.25.
	MaxDecrease *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=max_decrease,json=maxDecrease,proto3" json:"max_decrease,omitempty"`
	// Pressure at which “LOW“ participants reach their floor and “LIVE“ participants start
	// being squeezed. Defaults to 0.5.
	LiveSqueezeStart *wrapperspb.DoubleValue `protobuf:"bytes,5,opt,name=live_squeeze_start,json=liveSqueezeStart,proto3" json:"live_squeeze_start,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListenerBudgetConfig) Reset() {
	*x = ListenerBudgetConfig{}
	mi := &file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerBudgetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerBudgetConfig) ProtoMessage() {}

func (x *ListenerBudgetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerBudgetConfig.ProtoReflect.Descriptor instead.
func (*ListenerBudgetConfig) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDescGZIP(), []int{0}
}

func (x *ListenerBudgetConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListenerBudgetConfig) GetDefaultBurstHeadroom() uint64 {
	if x != nil {
		return x.DefaultBurstHeadroom
	}
	return 0
}

func (x *ListenerBudgetConfig) GetGrowthFactor() *wrapperspb.DoubleValue {
	if x != nil {
		return x.GrowthFactor
	}
	return nil
}

func (x *ListenerBudgetConfig) GetMaxDecrease() *wrapperspb.DoubleValue {
	if x != nil {
		return x.MaxDecrease
	}
	return nil
}

func (x *ListenerBudgetConfig) GetLiveSqueezeStart() *wrapperspb.DoubleValue {
	if x != nil {
		return x.LiveSqueezeStart
	}
	return nil
}

var File_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto protoreflect.FileDescriptor

const file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDesc = "" +
	"\n" +
	"Kenvoy/extensions/resource_monitors/listener_budget/v3/listener_budget.proto\x125envoy.extensions.resource_monitors.listener_budget.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\x84\x03\n" +
	"\x14ListenerBudgetConfig\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12=\n" +
	"\x16default_burst_headroom\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\x14defaultBurstHeadroom\x12Q\n" +
	"\rgrowth_factor\x18\x03 \x01(\v2\x1c.google.protobuf.DoubleValueB\x0e\xfaB\v\x12\t)\x00\x00\x00\x00\x00\x00\xf0?R\fgrowthFactor\x12X\n" +
	"\fmax_decrease\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueB\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?!\x00\x00\x00\x00\x00\x00\x00\x00R\vmaxDecrease\x12c\n" +
	"\x12live_squeeze_start\x18\x05 \x01(\v2\x1c.google.protobuf.DoubleValueB\x17\xfaB\x14\x12\x12\x11\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\x10liveSqueezeStartB\xd4\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"Cio.envoyproxy.envoy.extensions.resource_monitors.listener_budget.v3B\x13ListenerBudgetProtoP\x01Zngithub.com/envoyproxy/go-control-plane/envoy/extensions/resource_monitors/listener_budget/v3;listener_budgetv3b\x06proto3"

var (
	file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDescOnce sync.Once
	file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDescData []byte
)

func file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDescGZIP() []byte {
	file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDesc), len(file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDesc)))
	})
	return file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDescData
}

var file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_goTypes = []any{
	(*ListenerBudgetConfig)(nil),   // 0: envoy.extensions.resource_monitors.listener_budget.v3.ListenerBudgetConfig
	(*wrapperspb.DoubleValue)(nil), // 1: google.protobuf.DoubleValue
}
var file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_depIdxs = []int32{
	1, // 0: envoy.extensions.resource_monitors.listener_budget.v3.ListenerBudgetConfig.growth_factor:type_name -> google.protobuf.DoubleValue
	1, // 1: envoy.extensions.resource_monitors.listener_budget.v3.ListenerBudgetConfig.max_decrease:type_name -> google.protobuf.DoubleValue
	1, // 2: envoy.extensions.resource_monitors.listener_budget.v3.ListenerBudgetConfig.live_squeeze_start:type_name -> google.protobuf.DoubleValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_init() }
func file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_init() {
	if File_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDesc), len(file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_msgTypes,
	}.Build()
	File_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto = out.File
	file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_goTypes = nil
	file_envoy_extensions_resource_monitors_listener_budget_v3_listener_budget_proto_depIdxs = nil
}
