// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: envoy/extensions/resource_monitors/per_listener_downstream_connections/v3/per_listener_downstream_connections.proto

package per_listener_downstream_connectionsv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for a named connection budget. Participating Connection Limit Filters opt in via
// the matching “ConnectionBudget { name }“ block on the filter; the rebalancer distributes the
// budget across them on every overload manager refresh tick.
// [#next-free-field: 6]
type PerListenerDownstreamConnectionsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the budget. Filters opting in must specify the same name in their
	// “connection_budget“ block. Also used as the SingletonManager key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Total connections shared across all participating listeners. Required, > 0.
	//
	// At config load, “total_connections“ is cross-checked against
	// “envoy.resource_monitors.global_downstream_max_connections.max_active_downstream_connections“
	// when both monitors are configured in the same bootstrap; exceeding the global cap is
	// rejected because the listener accept layer would close connections this budget had allocated
	// quota for. The legacy runtime-key form
	// (“overload.global_downstream_max_connections“) is **not** cross-validated here; operators
	// using it must size “total_connections“ manually.
	TotalConnections uint64 `protobuf:"varint,2,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	// Minimum allocation any participating listener gets, even when idle. Defaults to 1.
	// Adding a listener that would push “N * min_listener_quota > total_connections“ is rejected
	// at registration.
	MinListenerQuota uint64 `protobuf:"varint,3,opt,name=min_listener_quota,json=minListenerQuota,proto3" json:"min_listener_quota,omitempty"`
	// Fractional headroom granted above a listener's current usage, in [0, 1]. With
	// “safety_margin = 0.10“ a listener at 500 connections receives a cap of at least 550
	// (subject to budget availability), so normal traffic variation does not push it into the
	// rejection range. Defaults to 0.
	SafetyMargin float64 `protobuf:"fixed64,4,opt,name=safety_margin,json=safetyMargin,proto3" json:"safety_margin,omitempty"`
	// Fraction of “total_connections“ strictly above which per-listener weighting engages, in
	// [0, 1]. While “sum_of_current_connections / total_connections <= pressure_threshold“ the
	// algorithm is unchanged; once it strictly exceeds the threshold, each tier's per-listener
	// demand is scaled by the filter-side “weight“ (see
	// “envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit.ConnectionBudget.weight“)
	// and freed capacity flows naturally to the remaining listeners. Optional: when unset, the
	// budget runs as if “pressure_threshold = 1.0“ (the strict “>“ check is never satisfied
	// because the ratio cannot exceed 1.0, so pressure mode is effectively off). Set to a value
	// less than 1.0 (e.g. 0.8) to opt in. An explicit “0.0“ keeps pressure mode active
	// whenever there is any usage at all.
	PressureThreshold *wrapperspb.DoubleValue `protobuf:"bytes,5,opt,name=pressure_threshold,json=pressureThreshold,proto3" json:"pressure_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PerListenerDownstreamConnectionsConfig) Reset() {
	*x = PerListenerDownstreamConnectionsConfig{}
	mi := &file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerListenerDownstreamConnectionsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerListenerDownstreamConnectionsConfig) ProtoMessage() {}

func (x *PerListenerDownstreamConnectionsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerListenerDownstreamConnectionsConfig.ProtoReflect.Descriptor instead.
func (*PerListenerDownstreamConnectionsConfig) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDescGZIP(), []int{0}
}

func (x *PerListenerDownstreamConnectionsConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PerListenerDownstreamConnectionsConfig) GetTotalConnections() uint64 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *PerListenerDownstreamConnectionsConfig) GetMinListenerQuota() uint64 {
	if x != nil {
		return x.MinListenerQuota
	}
	return 0
}

func (x *PerListenerDownstreamConnectionsConfig) GetSafetyMargin() float64 {
	if x != nil {
		return x.SafetyMargin
	}
	return 0
}

func (x *PerListenerDownstreamConnectionsConfig) GetPressureThreshold() *wrapperspb.DoubleValue {
	if x != nil {
		return x.PressureThreshold
	}
	return nil
}

var File_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto protoreflect.FileDescriptor

const file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDesc = "" +
	"\n" +
	"senvoy/extensions/resource_monitors/per_listener_downstream_connections/v3/per_listener_downstream_connections.proto\x12Ienvoy.extensions.resource_monitors.per_listener_downstream_connections.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xcd\x02\n" +
	"&PerListenerDownstreamConnectionsConfig\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x124\n" +
	"\x11total_connections\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\x10totalConnections\x12,\n" +
	"\x12min_listener_quota\x18\x03 \x01(\x04R\x10minListenerQuota\x12<\n" +
	"\rsafety_margin\x18\x04 \x01(\x01B\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\fsafetyMargin\x12d\n" +
	"\x12pressure_threshold\x18\x05 \x01(\v2\x1c.google.protobuf.DoubleValueB\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\x11pressureThresholdB\xa3\x02\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"Wio.envoyproxy.envoy.extensions.resource_monitors.per_listener_downstream_connections.v3B%PerListenerDownstreamConnectionsProtoP\x01Z\x96\x01github.com/envoyproxy/go-control-plane/envoy/extensions/resource_monitors/per_listener_downstream_connections/v3;per_listener_downstream_connectionsv3b\x06proto3"

var (
	file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDescOnce sync.Once
	file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDescData []byte
)

func file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDescGZIP() []byte {
	file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDesc), len(file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDesc)))
	})
	return file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDescData
}

var file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_goTypes = []any{
	(*PerListenerDownstreamConnectionsConfig)(nil), // 0: envoy.extensions.resource_monitors.per_listener_downstream_connections.v3.PerListenerDownstreamConnectionsConfig
	(*wrapperspb.DoubleValue)(nil),                 // 1: google.protobuf.DoubleValue
}
var file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_depIdxs = []int32{
	1, // 0: envoy.extensions.resource_monitors.per_listener_downstream_connections.v3.PerListenerDownstreamConnectionsConfig.pressure_threshold:type_name -> google.protobuf.DoubleValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_init()
}
func file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_init() {
	if File_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDesc), len(file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_msgTypes,
	}.Build()
	File_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto = out.File
	file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_goTypes = nil
	file_envoy_extensions_resource_monitors_per_listener_downstream_connections_v3_per_listener_downstream_connections_proto_depIdxs = nil
}
