// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: envoy/extensions/common/listener_budget/v3/listener_budget.proto

package listener_budgetv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenerBudgetParticipant_Priority int32

const (
	// Live traffic. Squeezed only once every “LOW“ participant is at its floor, and then only
	// when using more than its weighted fair share.
	ListenerBudgetParticipant_LIVE ListenerBudgetParticipant_Priority = 0
	// Traffic that must never hurt live traffic. Squeezed first under pressure, down to “min“.
	ListenerBudgetParticipant_LOW ListenerBudgetParticipant_Priority = 1
)

// Enum value maps for ListenerBudgetParticipant_Priority.
var (
	ListenerBudgetParticipant_Priority_name = map[int32]string{
		0: "LIVE",
		1: "LOW",
	}
	ListenerBudgetParticipant_Priority_value = map[string]int32{
		"LIVE": 0,
		"LOW":  1,
	}
)

func (x ListenerBudgetParticipant_Priority) Enum() *ListenerBudgetParticipant_Priority {
	p := new(ListenerBudgetParticipant_Priority)
	*p = x
	return p
}

func (x ListenerBudgetParticipant_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenerBudgetParticipant_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_enumTypes[0].Descriptor()
}

func (ListenerBudgetParticipant_Priority) Type() protoreflect.EnumType {
	return &file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_enumTypes[0]
}

func (x ListenerBudgetParticipant_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenerBudgetParticipant_Priority.Descriptor instead.
func (ListenerBudgetParticipant_Priority) EnumDescriptor() ([]byte, []int) {
	return file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDescGZIP(), []int{0, 0}
}

// How a filter joins the listener budget declared by the
// :ref:`envoy.resource_monitors.listener_budget
// <envoy_v3_api_msg_extensions.resource_monitors.listener_budget.v3.ListenerBudgetConfig>`
// resource monitor. Every filter chain of a listener that joins with the same kind of filter forms
// one participant: the chains admit against one shared counter and one limit, which the budget
// recomputes on every overload manager refresh tick. Chains of one listener should declare
// identical settings; when they differ, the most recent registration wins.
//
// Without pressure, a participant's limit follows its peak usage plus “burst_headroom“, and a
// participant that reached its limit gets it multiplied by the budget's “growth_factor“ on the
// next tick. Under pressure, limits stop growing and are squeezed: “LOW“ participants first,
// down to “min“, then the “LIVE“ participants using more than their weighted fair share.
// [#next-free-field: 7]
type ListenerBudgetParticipant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the budget to join: the “name“ of the “ListenerBudgetConfig“.
	BudgetName string `protobuf:"bytes,1,opt,name=budget_name,json=budgetName,proto3" json:"budget_name,omitempty"`
	// Priority class of this participant.
	Priority ListenerBudgetParticipant_Priority `protobuf:"varint,2,opt,name=priority,proto3,enum=envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant_Priority" json:"priority,omitempty"`
	// Weight of this participant in the fair share computed among “LIVE“ participants of the same
	// unit under pressure. Defaults to 1.0.
	Weight *wrapperspb.DoubleValue `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
	// Floor: the limit never goes below this value, under pressure included. Defaults to 0.
	Min uint64 `protobuf:"varint,4,opt,name=min,proto3" json:"min,omitempty"`
	// Cap: the limit never goes above this value. Must be greater than or equal to “min“. No cap
	// when unset.
	Max *wrapperspb.UInt64Value `protobuf:"bytes,5,opt,name=max,proto3" json:"max,omitempty"`
	// Room granted above the participant's peak usage, in its own unit (connections or requests).
	// A burst larger than this within one refresh tick is rejected on this listener only. Defaults
	// to the budget's “default_burst_headroom“.
	BurstHeadroom *wrapperspb.UInt64Value `protobuf:"bytes,6,opt,name=burst_headroom,json=burstHeadroom,proto3" json:"burst_headroom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerBudgetParticipant) Reset() {
	*x = ListenerBudgetParticipant{}
	mi := &file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerBudgetParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerBudgetParticipant) ProtoMessage() {}

func (x *ListenerBudgetParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerBudgetParticipant.ProtoReflect.Descriptor instead.
func (*ListenerBudgetParticipant) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDescGZIP(), []int{0}
}

func (x *ListenerBudgetParticipant) GetBudgetName() string {
	if x != nil {
		return x.BudgetName
	}
	return ""
}

func (x *ListenerBudgetParticipant) GetPriority() ListenerBudgetParticipant_Priority {
	if x != nil {
		return x.Priority
	}
	return ListenerBudgetParticipant_LIVE
}

func (x *ListenerBudgetParticipant) GetWeight() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *ListenerBudgetParticipant) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ListenerBudgetParticipant) GetMax() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *ListenerBudgetParticipant) GetBurstHeadroom() *wrapperspb.UInt64Value {
	if x != nil {
		return x.BurstHeadroom
	}
	return nil
}

var File_envoy_extensions_common_listener_budget_v3_listener_budget_proto protoreflect.FileDescriptor

const file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDesc = "" +
	"\n" +
	"@envoy/extensions/common/listener_budget/v3/listener_budget.proto\x12*envoy.extensions.common.listener_budget.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xb9\x03\n" +
	"\x19ListenerBudgetParticipant\x12(\n" +
	"\vbudget_name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"budgetName\x12t\n" +
	"\bpriority\x18\x02 \x01(\x0e2N.envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant.PriorityB\b\xfaB\x05\x82\x01\x02\x10\x01R\bpriority\x12D\n" +
	"\x06weight\x18\x03 \x01(\v2\x1c.google.protobuf.DoubleValueB\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06weight\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x04R\x03min\x127\n" +
	"\x03max\x18\x05 \x01(\v2\x1c.google.protobuf.UInt64ValueB\a\xfaB\x042\x02(\x01R\x03max\x12L\n" +
	"\x0eburst_headroom\x18\x06 \x01(\v2\x1c.google.protobuf.UInt64ValueB\a\xfaB\x042\x02(\x01R\rburstHeadroom\"\x1d\n" +
	"\bPriority\x12\b\n" +
	"\x04LIVE\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01B\xbe\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"8io.envoyproxy.envoy.extensions.common.listener_budget.v3B\x13ListenerBudgetProtoP\x01Zcgithub.com/envoyproxy/go-control-plane/envoy/extensions/common/listener_budget/v3;listener_budgetv3b\x06proto3"

var (
	file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDescOnce sync.Once
	file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDescData []byte
)

func file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDescGZIP() []byte {
	file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDesc), len(file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDesc)))
	})
	return file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDescData
}

var file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_goTypes = []any{
	(ListenerBudgetParticipant_Priority)(0), // 0: envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant.Priority
	(*ListenerBudgetParticipant)(nil),       // 1: envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant
	(*wrapperspb.DoubleValue)(nil),          // 2: google.protobuf.DoubleValue
	(*wrapperspb.UInt64Value)(nil),          // 3: google.protobuf.UInt64Value
}
var file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_depIdxs = []int32{
	0, // 0: envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant.priority:type_name -> envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant.Priority
	2, // 1: envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant.weight:type_name -> google.protobuf.DoubleValue
	3, // 2: envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant.max:type_name -> google.protobuf.UInt64Value
	3, // 3: envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant.burst_headroom:type_name -> google.protobuf.UInt64Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_init() }
func file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_init() {
	if File_envoy_extensions_common_listener_budget_v3_listener_budget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDesc), len(file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_depIdxs,
		EnumInfos:         file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_enumTypes,
		MessageInfos:      file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_msgTypes,
	}.Build()
	File_envoy_extensions_common_listener_budget_v3_listener_budget_proto = out.File
	file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_goTypes = nil
	file_envoy_extensions_common_listener_budget_v3_listener_budget_proto_depIdxs = nil
}
