//go:build !disable_pgv
// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/extensions/common/listener_budget/v3/listener_budget.proto

package listener_budgetv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListenerBudgetParticipant with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListenerBudgetParticipant) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListenerBudgetParticipant with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListenerBudgetParticipantMultiError, or nil if none found.
func (m *ListenerBudgetParticipant) ValidateAll() error {
	return m.validate(true)
}

func (m *ListenerBudgetParticipant) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBudgetName()) < 1 {
		err := ListenerBudgetParticipantValidationError{
			field:  "BudgetName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := ListenerBudgetParticipant_Priority_name[int32(m.GetPriority())]; !ok {
		err := ListenerBudgetParticipantValidationError{
			field:  "Priority",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if wrapper := m.GetWeight(); wrapper != nil {

		if wrapper.GetValue() <= 0 {
			err := ListenerBudgetParticipantValidationError{
				field:  "Weight",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for Min

	if wrapper := m.GetMax(); wrapper != nil {

		if wrapper.GetValue() < 1 {
			err := ListenerBudgetParticipantValidationError{
				field:  "Max",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if wrapper := m.GetBurstHeadroom(); wrapper != nil {

		if wrapper.GetValue() < 1 {
			err := ListenerBudgetParticipantValidationError{
				field:  "BurstHeadroom",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ListenerBudgetParticipantMultiError(errors)
	}

	return nil
}

// ListenerBudgetParticipantMultiError is an error wrapping multiple validation
// errors returned by ListenerBudgetParticipant.ValidateAll() if the
// designated constraints aren't met.
type ListenerBudgetParticipantMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListenerBudgetParticipantMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListenerBudgetParticipantMultiError) AllErrors() []error { return m }

// ListenerBudgetParticipantValidationError is the validation error returned by
// ListenerBudgetParticipant.Validate if the designated constraints aren't met.
type ListenerBudgetParticipantValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListenerBudgetParticipantValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListenerBudgetParticipantValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListenerBudgetParticipantValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListenerBudgetParticipantValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListenerBudgetParticipantValidationError) ErrorName() string {
	return "ListenerBudgetParticipantValidationError"
}

// Error satisfies the builtin error interface
func (e ListenerBudgetParticipantValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListenerBudgetParticipant.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListenerBudgetParticipantValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListenerBudgetParticipantValidationError{}
