// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: envoy/extensions/filters/http/request_limit/v3/request_limit.proto

package request_limitv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	v31 "github.com/envoyproxy/go-control-plane/envoy/extensions/common/listener_budget/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Limits the number of requests in flight. A request is counted from its headers until its stream
// ends; a request over the limit is answered with a 503 local reply (response code details
// “request_limit_exceeded“). HTTP/2 and HTTP/3 multiplex many requests on one connection, so a
// connection limit alone does not bound their load; this filter does.
//
// Emitted statistics, rooted at “<stat_prefix of the HTTP connection manager>request_limit.<stat_prefix>.“:
// counter “limited_requests“ and gauge “active_requests“.
type RequestLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix of the filter's statistics.
	StatPrefix string `protobuf:"bytes,1,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// Maximum number of requests in flight through this filter configuration. Replaced by the budget
	// when “listener_budget“ is set and the budget exists. No limit when unset.
	MaxRequests *wrapperspb.UInt64Value `protobuf:"bytes,2,opt,name=max_requests,json=maxRequests,proto3" json:"max_requests,omitempty"`
	// Runtime flag that controls whether the filter is enabled. Enabled when unset.
	RuntimeEnabled *v3.RuntimeFeatureFlag `protobuf:"bytes,3,opt,name=runtime_enabled,json=runtimeEnabled,proto3" json:"runtime_enabled,omitempty"`
	// Join a :ref:`listener budget
	// <envoy_v3_api_msg_extensions.resource_monitors.listener_budget.v3.ListenerBudgetConfig>`:
	// the budget then recomputes the limit on every overload manager refresh tick, shared by every
	// filter chain of the listener that joins it. When no budget with that name is configured,
	// “max_requests“ applies and a warning is logged.
	ListenerBudget *v31.ListenerBudgetParticipant `protobuf:"bytes,4,opt,name=listener_budget,json=listenerBudget,proto3" json:"listener_budget,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestLimit) Reset() {
	*x = RequestLimit{}
	mi := &file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLimit) ProtoMessage() {}

func (x *RequestLimit) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLimit.ProtoReflect.Descriptor instead.
func (*RequestLimit) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDescGZIP(), []int{0}
}

func (x *RequestLimit) GetStatPrefix() string {
	if x != nil {
		return x.StatPrefix
	}
	return ""
}

func (x *RequestLimit) GetMaxRequests() *wrapperspb.UInt64Value {
	if x != nil {
		return x.MaxRequests
	}
	return nil
}

func (x *RequestLimit) GetRuntimeEnabled() *v3.RuntimeFeatureFlag {
	if x != nil {
		return x.RuntimeEnabled
	}
	return nil
}

func (x *RequestLimit) GetListenerBudget() *v31.ListenerBudgetParticipant {
	if x != nil {
		return x.ListenerBudget
	}
	return nil
}

var File_envoy_extensions_filters_http_request_limit_v3_request_limit_proto protoreflect.FileDescriptor

const file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDesc = "" +
	"\n" +
	"Benvoy/extensions/filters/http/request_limit/v3/request_limit.proto\x12.envoy.extensions.filters.http.request_limit.v3\x1a\x1fenvoy/config/core/v3/base.proto\x1a@envoy/extensions/common/listener_budget/v3/listener_budget.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xc5\x02\n" +
	"\fRequestLimit\x12(\n" +
	"\vstat_prefix\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"statPrefix\x12H\n" +
	"\fmax_requests\x18\x02 \x01(\v2\x1c.google.protobuf.UInt64ValueB\a\xfaB\x042\x02(\x01R\vmaxRequests\x12Q\n" +
	"\x0fruntime_enabled\x18\x03 \x01(\v2(.envoy.config.core.v3.RuntimeFeatureFlagR\x0eruntimeEnabled\x12n\n" +
	"\x0flistener_budget\x18\x04 \x01(\v2E.envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipantR\x0elistenerBudgetB\xc2\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"<io.envoyproxy.envoy.extensions.filters.http.request_limit.v3B\x11RequestLimitProtoP\x01Zegithub.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/request_limit/v3;request_limitv3b\x06proto3"

var (
	file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDescOnce sync.Once
	file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDescData []byte
)

func file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDescGZIP() []byte {
	file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDesc), len(file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDesc)))
	})
	return file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDescData
}

var file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_goTypes = []any{
	(*RequestLimit)(nil),                  // 0: envoy.extensions.filters.http.request_limit.v3.RequestLimit
	(*wrapperspb.UInt64Value)(nil),        // 1: google.protobuf.UInt64Value
	(*v3.RuntimeFeatureFlag)(nil),         // 2: envoy.config.core.v3.RuntimeFeatureFlag
	(*v31.ListenerBudgetParticipant)(nil), // 3: envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant
}
var file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_depIdxs = []int32{
	1, // 0: envoy.extensions.filters.http.request_limit.v3.RequestLimit.max_requests:type_name -> google.protobuf.UInt64Value
	2, // 1: envoy.extensions.filters.http.request_limit.v3.RequestLimit.runtime_enabled:type_name -> envoy.config.core.v3.RuntimeFeatureFlag
	3, // 2: envoy.extensions.filters.http.request_limit.v3.RequestLimit.listener_budget:type_name -> envoy.extensions.common.listener_budget.v3.ListenerBudgetParticipant
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_init() }
func file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_init() {
	if File_envoy_extensions_filters_http_request_limit_v3_request_limit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDesc), len(file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_msgTypes,
	}.Build()
	File_envoy_extensions_filters_http_request_limit_v3_request_limit_proto = out.File
	file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_goTypes = nil
	file_envoy_extensions_filters_http_request_limit_v3_request_limit_proto_depIdxs = nil
}
