// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: examples/shardingtable/proto/sds.proto

package resource

import (
	_ "github.com/envoyproxy/go-control-plane/envoy/annotations"
	v3 "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_examples_shardingtable_proto_sds_proto protoreflect.FileDescriptor

const file_examples_shardingtable_proto_sds_proto_rawDesc = "" +
	"\n" +
	"&examples/shardingtable/proto/sds.proto\x12\x10shardingtable.v1\x1a*envoy/service/discovery/v3/discovery.proto\x1a envoy/annotations/resource.proto2\xcc\x03\n" +
	"\x18ShardingDiscoveryService\x12y\n" +
	"\x14StreamShardingTables\x12,.envoy.service.discovery.v3.DiscoveryRequest\x1a-.envoy.service.discovery.v3.DiscoveryResponse\"\x00(\x010\x01\x12t\n" +
	"\x13FetchShardingTables\x12,.envoy.service.discovery.v3.DiscoveryRequest\x1a-.envoy.service.discovery.v3.DiscoveryResponse\"\x00\x12\x82\x01\n" +
	"\x13DeltaShardingTables\x121.envoy.service.discovery.v3.DeltaDiscoveryRequest\x1a2.envoy.service.discovery.v3.DeltaDiscoveryResponse\"\x00(\x010\x01\x1a:\x8a\xa4\x96\xf3\a4\n" +
	"2type.googleapis.com/shardingtable.v1.ShardingTableBQZOgithub.com/envoyproxy/go-control-plane/examples/shardingtable/resource;resourceb\x06proto3"

var file_examples_shardingtable_proto_sds_proto_goTypes = []any{
	(*v3.DiscoveryRequest)(nil),       // 0: envoy.service.discovery.v3.DiscoveryRequest
	(*v3.DeltaDiscoveryRequest)(nil),  // 1: envoy.service.discovery.v3.DeltaDiscoveryRequest
	(*v3.DiscoveryResponse)(nil),      // 2: envoy.service.discovery.v3.DiscoveryResponse
	(*v3.DeltaDiscoveryResponse)(nil), // 3: envoy.service.discovery.v3.DeltaDiscoveryResponse
}
var file_examples_shardingtable_proto_sds_proto_depIdxs = []int32{
	0, // 0: shardingtable.v1.ShardingDiscoveryService.StreamShardingTables:input_type -> envoy.service.discovery.v3.DiscoveryRequest
	0, // 1: shardingtable.v1.ShardingDiscoveryService.FetchShardingTables:input_type -> envoy.service.discovery.v3.DiscoveryRequest
	1, // 2: shardingtable.v1.ShardingDiscoveryService.DeltaShardingTables:input_type -> envoy.service.discovery.v3.DeltaDiscoveryRequest
	2, // 3: shardingtable.v1.ShardingDiscoveryService.StreamShardingTables:output_type -> envoy.service.discovery.v3.DiscoveryResponse
	2, // 4: shardingtable.v1.ShardingDiscoveryService.FetchShardingTables:output_type -> envoy.service.discovery.v3.DiscoveryResponse
	3, // 5: shardingtable.v1.ShardingDiscoveryService.DeltaShardingTables:output_type -> envoy.service.discovery.v3.DeltaDiscoveryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_shardingtable_proto_sds_proto_init() }
func file_examples_shardingtable_proto_sds_proto_init() {
	if File_examples_shardingtable_proto_sds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_shardingtable_proto_sds_proto_rawDesc), len(file_examples_shardingtable_proto_sds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_shardingtable_proto_sds_proto_goTypes,
		DependencyIndexes: file_examples_shardingtable_proto_sds_proto_depIdxs,
	}.Build()
	File_examples_shardingtable_proto_sds_proto = out.File
	file_examples_shardingtable_proto_sds_proto_goTypes = nil
	file_examples_shardingtable_proto_sds_proto_depIdxs = nil
}
