// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: examples/shardingtable/proto/sds.proto

package resource

import (
	context "context"
	v3 "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardingDiscoveryService_StreamShardingTables_FullMethodName = "/shardingtable.v1.ShardingDiscoveryService/StreamShardingTables"
	ShardingDiscoveryService_FetchShardingTables_FullMethodName  = "/shardingtable.v1.ShardingDiscoveryService/FetchShardingTables"
	ShardingDiscoveryService_DeltaShardingTables_FullMethodName  = "/shardingtable.v1.ShardingDiscoveryService/DeltaShardingTables"
)

// ShardingDiscoveryServiceClient is the client API for ShardingDiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardingDiscoveryServiceClient interface {
	StreamShardingTables(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v3.DiscoveryRequest, v3.DiscoveryResponse], error)
	FetchShardingTables(ctx context.Context, in *v3.DiscoveryRequest, opts ...grpc.CallOption) (*v3.DiscoveryResponse, error)
	DeltaShardingTables(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v3.DeltaDiscoveryRequest, v3.DeltaDiscoveryResponse], error)
}

type shardingDiscoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShardingDiscoveryServiceClient(cc grpc.ClientConnInterface) ShardingDiscoveryServiceClient {
	return &shardingDiscoveryServiceClient{cc}
}

func (c *shardingDiscoveryServiceClient) StreamShardingTables(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v3.DiscoveryRequest, v3.DiscoveryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShardingDiscoveryService_ServiceDesc.Streams[0], ShardingDiscoveryService_StreamShardingTables_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v3.DiscoveryRequest, v3.DiscoveryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardingDiscoveryService_StreamShardingTablesClient = grpc.BidiStreamingClient[v3.DiscoveryRequest, v3.DiscoveryResponse]

func (c *shardingDiscoveryServiceClient) FetchShardingTables(ctx context.Context, in *v3.DiscoveryRequest, opts ...grpc.CallOption) (*v3.DiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v3.DiscoveryResponse)
	err := c.cc.Invoke(ctx, ShardingDiscoveryService_FetchShardingTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardingDiscoveryServiceClient) DeltaShardingTables(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v3.DeltaDiscoveryRequest, v3.DeltaDiscoveryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShardingDiscoveryService_ServiceDesc.Streams[1], ShardingDiscoveryService_DeltaShardingTables_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v3.DeltaDiscoveryRequest, v3.DeltaDiscoveryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardingDiscoveryService_DeltaShardingTablesClient = grpc.BidiStreamingClient[v3.DeltaDiscoveryRequest, v3.DeltaDiscoveryResponse]

// ShardingDiscoveryServiceServer is the server API for ShardingDiscoveryService service.
// All implementations must embed UnimplementedShardingDiscoveryServiceServer
// for forward compatibility.
type ShardingDiscoveryServiceServer interface {
	StreamShardingTables(grpc.BidiStreamingServer[v3.DiscoveryRequest, v3.DiscoveryResponse]) error
	FetchShardingTables(context.Context, *v3.DiscoveryRequest) (*v3.DiscoveryResponse, error)
	DeltaShardingTables(grpc.BidiStreamingServer[v3.DeltaDiscoveryRequest, v3.DeltaDiscoveryResponse]) error
	mustEmbedUnimplementedShardingDiscoveryServiceServer()
}

// UnimplementedShardingDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardingDiscoveryServiceServer struct{}

func (UnimplementedShardingDiscoveryServiceServer) StreamShardingTables(grpc.BidiStreamingServer[v3.DiscoveryRequest, v3.DiscoveryResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamShardingTables not implemented")
}
func (UnimplementedShardingDiscoveryServiceServer) FetchShardingTables(context.Context, *v3.DiscoveryRequest) (*v3.DiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchShardingTables not implemented")
}
func (UnimplementedShardingDiscoveryServiceServer) DeltaShardingTables(grpc.BidiStreamingServer[v3.DeltaDiscoveryRequest, v3.DeltaDiscoveryResponse]) error {
	return status.Error(codes.Unimplemented, "method DeltaShardingTables not implemented")
}
func (UnimplementedShardingDiscoveryServiceServer) mustEmbedUnimplementedShardingDiscoveryServiceServer() {
}
func (UnimplementedShardingDiscoveryServiceServer) testEmbeddedByValue() {}

// UnsafeShardingDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardingDiscoveryServiceServer will
// result in compilation errors.
type UnsafeShardingDiscoveryServiceServer interface {
	mustEmbedUnimplementedShardingDiscoveryServiceServer()
}

func RegisterShardingDiscoveryServiceServer(s grpc.ServiceRegistrar, srv ShardingDiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedShardingDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardingDiscoveryService_ServiceDesc, srv)
}

func _ShardingDiscoveryService_StreamShardingTables_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShardingDiscoveryServiceServer).StreamShardingTables(&grpc.GenericServerStream[v3.DiscoveryRequest, v3.DiscoveryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardingDiscoveryService_StreamShardingTablesServer = grpc.BidiStreamingServer[v3.DiscoveryRequest, v3.DiscoveryResponse]

func _ShardingDiscoveryService_FetchShardingTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v3.DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardingDiscoveryServiceServer).FetchShardingTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardingDiscoveryService_FetchShardingTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardingDiscoveryServiceServer).FetchShardingTables(ctx, req.(*v3.DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardingDiscoveryService_DeltaShardingTables_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShardingDiscoveryServiceServer).DeltaShardingTables(&grpc.GenericServerStream[v3.DeltaDiscoveryRequest, v3.DeltaDiscoveryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardingDiscoveryService_DeltaShardingTablesServer = grpc.BidiStreamingServer[v3.DeltaDiscoveryRequest, v3.DeltaDiscoveryResponse]

// ShardingDiscoveryService_ServiceDesc is the grpc.ServiceDesc for ShardingDiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardingDiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shardingtable.v1.ShardingDiscoveryService",
	HandlerType: (*ShardingDiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchShardingTables",
			Handler:    _ShardingDiscoveryService_FetchShardingTables_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamShardingTables",
			Handler:       _ShardingDiscoveryService_StreamShardingTables_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DeltaShardingTables",
			Handler:       _ShardingDiscoveryService_DeltaShardingTables_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "examples/shardingtable/proto/sds.proto",
}
