// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: examples/shardingtable/proto/sharding_table.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardingTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardingTable) Reset() {
	*x = ShardingTable{}
	mi := &file_examples_shardingtable_proto_sharding_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardingTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardingTable) ProtoMessage() {}

func (x *ShardingTable) ProtoReflect() protoreflect.Message {
	mi := &file_examples_shardingtable_proto_sharding_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardingTable.ProtoReflect.Descriptor instead.
func (*ShardingTable) Descriptor() ([]byte, []int) {
	return file_examples_shardingtable_proto_sharding_table_proto_rawDescGZIP(), []int{0}
}

func (x *ShardingTable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShardingTable) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_examples_shardingtable_proto_sharding_table_proto protoreflect.FileDescriptor

const file_examples_shardingtable_proto_sharding_table_proto_rawDesc = "" +
	"\n" +
	"1examples/shardingtable/proto/sharding_table.proto\x12\x10shardingtable.v1\"=\n" +
	"\rShardingTable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentBQZOgithub.com/envoyproxy/go-control-plane/examples/shardingtable/resource;resourceb\x06proto3"

var (
	file_examples_shardingtable_proto_sharding_table_proto_rawDescOnce sync.Once
	file_examples_shardingtable_proto_sharding_table_proto_rawDescData []byte
)

func file_examples_shardingtable_proto_sharding_table_proto_rawDescGZIP() []byte {
	file_examples_shardingtable_proto_sharding_table_proto_rawDescOnce.Do(func() {
		file_examples_shardingtable_proto_sharding_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_shardingtable_proto_sharding_table_proto_rawDesc), len(file_examples_shardingtable_proto_sharding_table_proto_rawDesc)))
	})
	return file_examples_shardingtable_proto_sharding_table_proto_rawDescData
}

var file_examples_shardingtable_proto_sharding_table_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_shardingtable_proto_sharding_table_proto_goTypes = []any{
	(*ShardingTable)(nil), // 0: shardingtable.v1.ShardingTable
}
var file_examples_shardingtable_proto_sharding_table_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_shardingtable_proto_sharding_table_proto_init() }
func file_examples_shardingtable_proto_sharding_table_proto_init() {
	if File_examples_shardingtable_proto_sharding_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_shardingtable_proto_sharding_table_proto_rawDesc), len(file_examples_shardingtable_proto_sharding_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_shardingtable_proto_sharding_table_proto_goTypes,
		DependencyIndexes: file_examples_shardingtable_proto_sharding_table_proto_depIdxs,
		MessageInfos:      file_examples_shardingtable_proto_sharding_table_proto_msgTypes,
	}.Build()
	File_examples_shardingtable_proto_sharding_table_proto = out.File
	file_examples_shardingtable_proto_sharding_table_proto_goTypes = nil
	file_examples_shardingtable_proto_sharding_table_proto_depIdxs = nil
}
